name: Deploy Lambda Function

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'CocktailRecipeLookup.Lambda/**'
      - '.github/workflows/backend-build-deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Install Lambda Tools
      run: dotnet tool install -g Amazon.Lambda.Tools

    - name: Build and Package Lambda
      working-directory: ./CocktailRecipeLookup.Lambda
      run: |
        dotnet build --configuration Release
        dotnet lambda package -o function.zip

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Deploy to Lambda
      working-directory: ./CocktailRecipeLookup.Lambda
      run: |
        aws lambda update-function-code \
          --function-name CocktailRecipeApi \
          --zip-file fileb://function.zip
